apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    app: front-end

spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: javacontainer
        image:   pavithra123456789/javaimage:100
        ports:
        - containerPort: 80 
   

